// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduledTask;

#nullable disable

namespace ScheduledTask.Migrations
{
    [DbContext(typeof(QuartzContext))]
    partial class QuartzContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.BLOB_TRIGGERS", b =>
                {
                    b.Property<string>("SchedName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("SCHED_NAME")
                        .HasColumnOrder(0);

                    b.Property<string>("TriggerName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("TRIGGER_NAME")
                        .HasColumnOrder(1);

                    b.Property<string>("TriggerGroup")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("TRIGGER_GROUP")
                        .HasColumnOrder(2);

                    b.Property<byte[]>("BlobData")
                        .HasColumnType("longblob")
                        .HasColumnName("BLOB_DATA");

                    b.HasKey("SchedName", "TriggerName", "TriggerGroup");

                    b.ToTable("qrtz_blob_triggers", (string)null);
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.CALENDARS", b =>
                {
                    b.Property<string>("SchedName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("sched_name")
                        .HasColumnOrder(0);

                    b.Property<string>("CalendarName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("calendar_name")
                        .HasColumnOrder(1);

                    b.Property<byte[]>("Calendar")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("calendar");

                    b.HasKey("SchedName", "CalendarName");

                    b.ToTable("qrtz_calendars", (string)null);
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.CRON_TRIGGERS", b =>
                {
                    b.Property<string>("SchedName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("sched_name")
                        .HasColumnOrder(0);

                    b.Property<string>("TriggerName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("trigger_name")
                        .HasColumnOrder(1);

                    b.Property<string>("TriggerGroup")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("trigger_group")
                        .HasColumnOrder(2);

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("cron_expression");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("SchedName", "TriggerName", "TriggerGroup");

                    b.ToTable("qrtz_cron_triggers", (string)null);
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.FIRED_TRIGGERS", b =>
                {
                    b.Property<string>("SchedName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("sched_name")
                        .HasColumnOrder(0);

                    b.Property<string>("EntryId")
                        .HasMaxLength(95)
                        .HasColumnType("varchar(95)")
                        .HasColumnName("entry_id")
                        .HasColumnOrder(1);

                    b.Property<string>("TriggerName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("trigger_name")
                        .HasColumnOrder(2);

                    b.Property<string>("TriggerGroup")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("trigger_group")
                        .HasColumnOrder(3);

                    b.Property<long>("FiredTime")
                        .HasColumnType("bigint")
                        .HasColumnName("fired_time");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("instance_name");

                    b.Property<bool?>("IsNonConcurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_nonconcurrent");

                    b.Property<string>("JobGroup")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("job_group");

                    b.Property<string>("JobName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("job_name");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<bool?>("RequestsRecovery")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requests_recovery");

                    b.Property<long>("SchedTime")
                        .HasColumnType("bigint")
                        .HasColumnName("sched_time");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("state");

                    b.HasKey("SchedName", "EntryId", "TriggerName", "TriggerGroup");

                    b.ToTable("qrtz_fired_triggers", (string)null);
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.JOB_DETAILS", b =>
                {
                    b.Property<string>("SchedName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("sched_name")
                        .HasColumnOrder(0);

                    b.Property<string>("JobName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("job_name")
                        .HasColumnOrder(1);

                    b.Property<string>("JobGroup")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("job_group")
                        .HasColumnOrder(2);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDurable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_durable");

                    b.Property<bool>("IsNonConcurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_nonconcurrent");

                    b.Property<bool>("IsUpdateData")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_update_data");

                    b.Property<string>("JobClassName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("job_class_name");

                    b.Property<byte[]>("JobData")
                        .HasColumnType("longblob")
                        .HasColumnName("job_data");

                    b.Property<bool>("RequestsRecovery")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requests_recovery");

                    b.HasKey("SchedName", "JobName", "JobGroup");

                    b.ToTable("qrtz_job_details", (string)null);
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.JobConfig", b =>
                {
                    b.Property<string>("Group")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("GROUP");

                    b.Property<string>("JobKeyName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("JOB_KEYNAME");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CRON");

                    b.Property<string>("CronDescription")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CRON_DESC");

                    b.Property<string>("IsEnable")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N")
                        .HasColumnName("IS_ENABLE");

                    b.Property<string>("JobDescription")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("JOB_DESC");

                    b.Property<string>("TriggerDescription")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TRIGGER_DESC");

                    b.Property<string>("TriggerKeyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TRIGGER_KEYNAME");

                    b.HasKey("Group", "JobKeyName");

                    b.HasIndex("Group");

                    b.HasIndex("JobKeyName");

                    b.ToTable("JOB_CONFIG", (string)null);
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.LOCKS", b =>
                {
                    b.Property<string>("SchedName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("sched_name")
                        .HasColumnOrder(0);

                    b.Property<string>("LockName")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("lock_name")
                        .HasColumnOrder(1);

                    b.HasKey("SchedName", "LockName");

                    b.ToTable("qrtz_locks", (string)null);
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.PAUSED_TRIGGER_GRPS", b =>
                {
                    b.Property<string>("SchedName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("sched_name")
                        .HasColumnOrder(0);

                    b.Property<string>("TriggerGroup")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("trigger_group")
                        .HasColumnOrder(1);

                    b.HasKey("SchedName", "TriggerGroup");

                    b.ToTable("qrtz_paused_trigger_grps", (string)null);
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.SCHEDULER_STATE", b =>
                {
                    b.Property<string>("SchedName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("sched_name")
                        .HasColumnOrder(0);

                    b.Property<string>("InstanceName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("instance_name")
                        .HasColumnOrder(1);

                    b.Property<long>("CheckinInterval")
                        .HasColumnType("bigint")
                        .HasColumnName("checkin_interval");

                    b.Property<long>("LastCheckinTime")
                        .HasColumnType("bigint")
                        .HasColumnName("last_checkin_time");

                    b.HasKey("SchedName", "InstanceName");

                    b.ToTable("qrtz_scheduler_state", (string)null);
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.SIMPLE_TRIGGERS", b =>
                {
                    b.Property<string>("SchedName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("sched_name")
                        .HasColumnOrder(0);

                    b.Property<string>("TriggerName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("trigger_name")
                        .HasColumnOrder(1);

                    b.Property<string>("TriggerGroup")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("trigger_group")
                        .HasColumnOrder(2);

                    b.Property<long>("RepeatCount")
                        .HasColumnType("bigint")
                        .HasColumnName("repeat_count");

                    b.Property<long>("RepeatInterval")
                        .HasColumnType("bigint")
                        .HasColumnName("repeat_interval");

                    b.Property<long>("TimesTriggered")
                        .HasColumnType("bigint")
                        .HasColumnName("times_triggered");

                    b.HasKey("SchedName", "TriggerName", "TriggerGroup");

                    b.ToTable("qrtz_simple_triggers", (string)null);
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.SIMPROP_TRIGGERS", b =>
                {
                    b.Property<string>("SchedName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("sched_name")
                        .HasColumnOrder(0);

                    b.Property<string>("TriggerName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("trigger_name")
                        .HasColumnOrder(1);

                    b.Property<string>("TriggerGroup")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("trigger_group")
                        .HasColumnOrder(2);

                    b.Property<bool?>("BoolProp1")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("bool_prop_1");

                    b.Property<bool?>("BoolProp2")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("bool_prop_2");

                    b.Property<decimal?>("DecProp1")
                        .HasColumnType("numeric(13,4)")
                        .HasColumnName("dec_prop_1");

                    b.Property<decimal?>("DecProp2")
                        .HasColumnType("numeric(13,4)")
                        .HasColumnName("dec_prop_2");

                    b.Property<int?>("IntProp1")
                        .HasColumnType("int")
                        .HasColumnName("int_prop_1");

                    b.Property<int?>("IntProp2")
                        .HasColumnType("int")
                        .HasColumnName("int_prop_2");

                    b.Property<long?>("LongProp1")
                        .HasColumnType("bigint")
                        .HasColumnName("long_prop_1");

                    b.Property<long?>("LongProp2")
                        .HasColumnType("bigint")
                        .HasColumnName("long_prop_2");

                    b.Property<string>("StrProp1")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("str_prop_1");

                    b.Property<string>("StrProp2")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("str_prop_2");

                    b.Property<string>("StrProp3")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("str_prop_3");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("SchedName", "TriggerName", "TriggerGroup");

                    b.ToTable("qrtz_simprop_triggers", (string)null);
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.TRIGGERS", b =>
                {
                    b.Property<string>("SchedName")
                        .HasColumnType("varchar(120)")
                        .HasColumnName("sched_name")
                        .HasColumnOrder(0);

                    b.Property<string>("TriggerName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("trigger_name")
                        .HasColumnOrder(1);

                    b.Property<string>("TriggerGroup")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("trigger_group")
                        .HasColumnOrder(2);

                    b.Property<string>("CalendarName")
                        .HasColumnType("longtext")
                        .HasColumnName("calendar_name");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<long?>("EndTime")
                        .HasColumnType("bigint")
                        .HasColumnName("end_time");

                    b.Property<byte[]>("JobData")
                        .HasColumnType("longblob")
                        .HasColumnName("job_data");

                    b.Property<string>("JobGroup")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("job_group");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("job_name");

                    b.Property<short?>("MisfireInstr")
                        .HasColumnType("smallint")
                        .HasColumnName("misfire_instr");

                    b.Property<long?>("NextFireTime")
                        .HasColumnType("bigint")
                        .HasColumnName("next_fire_time");

                    b.Property<long?>("PrevFireTime")
                        .HasColumnType("bigint")
                        .HasColumnName("prev_fire_time");

                    b.Property<int?>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint")
                        .HasColumnName("start_time");

                    b.Property<string>("TriggerState")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trigger_state");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trigger_type");

                    b.HasKey("SchedName", "TriggerName", "TriggerGroup");

                    b.HasIndex("SchedName", "JobName", "JobGroup");

                    b.ToTable("qrtz_triggers", (string)null);
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.TRIGGERS", b =>
                {
                    b.HasOne("ScheduledTask.Domain.Persistence.JOB_DETAILS", "JobDetail")
                        .WithMany("Triggers")
                        .HasForeignKey("SchedName", "JobName", "JobGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TRIGGERS_JOB_DETAILS");

                    b.Navigation("JobDetail");
                });

            modelBuilder.Entity("ScheduledTask.Domain.Persistence.JOB_DETAILS", b =>
                {
                    b.Navigation("Triggers");
                });
#pragma warning restore 612, 618
        }
    }
}
